---
- setup:
    gather_subset: min

- name: Clone bare repository
  git:
    bare: yes
    force: true
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"

- name: Stash local changes/conflicts
  shell: >-
    git
    --git-dir="{{ dotfiles_repo_local_destination }}"
    --work-tree="{{ dotfiles_home }}"
    stash push
    --message "Ansible lsevcik.dotfiles {{ ansible_date_time['date'] }}"
  register: stash_result
  changed_when:
    - "'Saved' in stash_result.stdout"

- name: Set repository configuration
  git_config:
    name: status.showUntrackedFiles
    repo: "{{ dotfiles_repo_local_destination }}"
    scope: local
  when: not dotfiles_status_untracked_files
