---
- name: Clone bare repository
  git:
    bare: yes
    force: true
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"

- name: Stash local changes/conflicts
  shell: >-
    git
    --git-dir="{{ dotfiles_repo_local_destination }}"
    --work-tree="{{ dotfiles_home }}"
    stash push
    --message "Ansible lsevcik.dotfiles $(date -I)"
  register: stash_result
  changed_when:
    - "'Saved' in stash_result.stdout"

- name: Checkout master
  shell: >-
    git
    --git-dir="{{ dotfiles_repo_local_destination }}"
    --work-tree="{{ dotfiles_home }}"
    checkout -f
  changed_when:
    - false

- name: Set repository configuration
  shell: >-
    BEFORE=$(git
    --git-dir="{{ dotfiles_repo_local_destination }}"
    --work-tree="{{ dotfiles_home }}"
    config --local status.showUntrackedFiles);

    git
    --git-dir="{{ dotfiles_repo_local_destination }}"
    --work-tree="{{ dotfiles_home }}"
    config --local status.showUntrackedFiles no;

    AFTER="$(git
    --git-dir="{{ dotfiles_repo_local_destination }}"
    --work-tree="{{ dotfiles_home }}"
    config --local status.showUntrackedFiles)";

    if [ "$BEFORE" != "$AFTER" ]; then echo changed; fi;
  when: not dotfiles_status_untracked_files
  register: config_result
  changed_when:
    - "'changed' in config_result.stdout"
